module.exports = {
  sold: {
    id: 0,
    strength: 300,
    defence_melee: 1,
    defence_ranged: 15,
    damage: 40,
    fire_radius: 4,
    speed: 1,
    agility: 22,
    type: "sold",
    weapon: "gun",
    range: "ranged",
  },
  hero: {
    id: 0,
    strength: 200,
    defence_melee: 1,
    defence_ranged: 20,
    damage: 50,
    fire_radius: 4,
    speed: 1,
    agility: 25,
    type: "hero",
    weapon: "gun",
    range: "ranged",
  },
  samurai: {
    id: 0,
    strength: 400,
    defence_melee: 10,
    defence_ranged: 30,
    damage: 90,
    fire_radius: 1,
    speed: 2,
    agility: 20,
    type: "samurai",
    weapon: "sword",
    range: "melee",
  },
  bandit: {
    id: 0,
    strength: 350,
    defence_melee: 2,
    defence_ranged: 35,
    damage: 90,
    fire_radius: 1,
    speed: 2,
    agility: 25,
    type: "bandit",
    weapon: "sword",
    range: "melee",
  },
  goblin: {
    id: 0,
    strength: 550,
    defence_melee: 5,
    defence_ranged: 5,
    damage: 100,
    fire_radius: 1,
    speed: 1,
    agility: 15,
    type: "goblin",
    weapon: "sword",
    range: "melee",
  },
  knight: {
    id: 0,
    strength: 750,
    defence_melee: 30,
    defence_ranged: 0,
    damage: 80,
    fire_radius: 1,
    speed: 1,
    agility: 10,
    type: "knight",
    weapon: "sword",
    range: "melee",
  },
  //   warrior: {
  //     id: 0,
  //     hp: 750,
  //     strength: 750,
  //     damage: 80,
  //     fire_radius: 1,
  //     speed: 1,
  //     agility: 10,
  //     type: "warrior",
  //     weapon: "sword",
  //   },
};
