module.exports = {
  sold: {
    id: 0,
    hp: 300,
    strength: 300,
    damage: 20,
    fire_radius: 4,
    speed: 1,
    agility: 50,
    type: "sold",
    weapon: "gun",
  },
  hero: {
    id: 0,
    hp: 200,
    strength: 200,
    damage: 30,
    fire_radius: 4,
    speed: 1,
    agility: 60,
    type: "hero",
    weapon: "gun",
  },
  samurai: {
    id: 0,
    hp: 400,
    strength: 400,
    damage: 90,
    fire_radius: 1,
    speed: 2,
    agility: 30,
    type: "samurai",
    weapon: "sword",
  },
  bandit: {
    id: 0,
    hp: 350,
    strength: 350,
    damage: 90,
    fire_radius: 1,
    speed: 2,
    agility: 50,
    type: "bandit",
    weapon: "sword",
  },
  goblin: {
    id: 0,
    hp: 550,
    strength: 550,
    damage: 100,
    fire_radius: 1,
    speed: 1,
    agility: 20,
    type: "goblin",
    weapon: "sword",
  },
  knight: {
    id: 0,
    hp: 750,
    strength: 750,
    damage: 80,
    fire_radius: 1,
    speed: 1,
    agility: 10,
    type: "knight",
    weapon: "sword",
  },
};
