module.exports = {
  sold: {
    id: 0,
    strength: 300,
    defence_melee: 1,
    defence_ranged: 15,
    damage: 35,
    fire_radius: 4,
    speed: 1,
    agility: 22,
    type: "sold",
    weapon: "gun",
    range: "ranged",
  },
  hero: {
    id: 0,
    strength: 250,
    defence_melee: 1,
    defence_ranged: 20,
    damage: 40,
    fire_radius: 4,
    speed: 1,
    agility: 25,
    type: "hero",
    weapon: "gun",
    range: "ranged",
  },
  samurai: {
    id: 0,
    strength: 400,
    defence_melee: 10,
    defence_ranged: 30,
    damage: 60,
    fire_radius: 1,
    speed: 2,
    agility: 20,
    type: "samurai",
    weapon: "sword",
    range: "melee",
  },
  bandit: {
    id: 0,
    strength: 350,
    defence_melee: 2,
    defence_ranged: 35,
    damage: 60,
    fire_radius: 1,
    speed: 2,
    agility: 25,
    type: "bandit",
    weapon: "sword",
    range: "melee",
  },
  goblin: {
    id: 0,
    strength: 450,
    defence_melee: 5,
    defence_ranged: 5,
    damage: 65,
    fire_radius: 1,
    speed: 1,
    agility: 15,
    type: "goblin",
    weapon: "sword",
    range: "melee",
  },
  knight: {
    id: 0,
    strength: 500,
    defence_melee: 30,
    defence_ranged: 0,
    damage: 50,
    fire_radius: 1,
    speed: 1,
    agility: 10,
    type: "knight",
    weapon: "sword",
    range: "melee",
  },
};
